version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-signup-signin-api-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m733pte47ym6"
s3_prefix = "demo-signup-signin-api-lambda"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
